//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Unit05.Example2.Web.WSClient.ApplicationWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zone", Namespace="http://ws.unit05.example2/application/")]
    public enum Zone : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CENTER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EAST = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEST = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://ws.unit05.example2/application/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private double ProductPriceField;
        
        private double ShippingPriceField;
        
        private long VisitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double ShippingPrice {
            get {
                return this.ShippingPriceField;
            }
            set {
                if ((this.ShippingPriceField.Equals(value) != true)) {
                    this.ShippingPriceField = value;
                    this.RaisePropertyChanged("ShippingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Visits {
            get {
                return this.VisitsField;
            }
            set {
                if ((this.VisitsField.Equals(value) != true)) {
                    this.VisitsField = value;
                    this.RaisePropertyChanged("Visits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ws.unit05.example2/application/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unit05.example2/application/", ConfigurationName="WSClient.ApplicationWS.ApplicationServicesSoap")]
    public interface ApplicationServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://ws.unit05.example2/application/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2/application/GetProduct", ReplyAction="*")]
        WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse GetProduct(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2/application/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse> GetProductAsync(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetProductsResult del espacio de nombres http://ws.unit05.example2/application/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2/application/GetProducts", ReplyAction="*")]
        WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse GetProducts(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2/application/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse> GetProductsAsync(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://ws.unit05.example2/application/", Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequestBody Body;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2/application/")]
    public partial class GetProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.Zone zone;
        
        public GetProductRequestBody() {
        }
        
        public GetProductRequestBody(string name, WS.Unit05.Example2.Web.WSClient.ApplicationWS.Zone zone) {
            this.name = name;
            this.zone = zone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://ws.unit05.example2/application/", Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponseBody Body;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2/application/")]
    public partial class GetProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.Product GetProductResult;
        
        public GetProductResponseBody() {
        }
        
        public GetProductResponseBody(WS.Unit05.Example2.Web.WSClient.ApplicationWS.Product GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://ws.unit05.example2/application/", Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://ws.unit05.example2/application/", Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2/application/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.ArrayOfString GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(WS.Unit05.Example2.Web.WSClient.ApplicationWS.ArrayOfString GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationServicesSoapChannel : WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServicesSoapClient : System.ServiceModel.ClientBase<WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap>, WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap {
        
        public ApplicationServicesSoapClient() {
        }
        
        public ApplicationServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap.GetProduct(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.Product GetProduct(string name, WS.Unit05.Example2.Web.WSClient.ApplicationWS.Zone zone) {
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest inValue = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest();
            inValue.Body = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequestBody();
            inValue.Body.name = name;
            inValue.Body.zone = zone;
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse retVal = ((WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap)(this)).GetProduct(inValue);
            return retVal.Body.GetProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse> WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap.GetProductAsync(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest request) {
            return base.Channel.GetProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductResponse> GetProductAsync(string name, WS.Unit05.Example2.Web.WSClient.ApplicationWS.Zone zone) {
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest inValue = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequest();
            inValue.Body = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductRequestBody();
            inValue.Body.name = name;
            inValue.Body.zone = zone;
            return ((WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap)(this)).GetProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap.GetProducts(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public WS.Unit05.Example2.Web.WSClient.ApplicationWS.ArrayOfString GetProducts() {
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest inValue = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest();
            inValue.Body = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequestBody();
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse retVal = ((WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse> WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap.GetProductsAsync(WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsResponse> GetProductsAsync() {
            WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest inValue = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequest();
            inValue.Body = new WS.Unit05.Example2.Web.WSClient.ApplicationWS.GetProductsRequestBody();
            return ((WS.Unit05.Example2.Web.WSClient.ApplicationWS.ApplicationServicesSoap)(this)).GetProductsAsync(inValue);
        }
    }
}
