//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Unit05.Example2.Application.WSClient.DataWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistics", Namespace="http://ws.unit05.example2-data/")]
    [System.SerializableAttribute()]
    public partial class Statistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private long VisitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Visits {
            get {
                return this.VisitsField;
            }
            set {
                if ((this.VisitsField.Equals(value) != true)) {
                    this.VisitsField = value;
                    this.RaisePropertyChanged("Visits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unit05.example2-data/", ConfigurationName="WSClient.DataWS.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetStatisticsResult del espacio de nombres http://ws.unit05.example2-data/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/GetStatistics", ReplyAction="*")]
        WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse GetStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/GetStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse> GetStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://ws.unit05.example2-data/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/GetProductStatistics", ReplyAction="*")]
        WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse GetProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/GetProductStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse> GetProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://ws.unit05.example2-data/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/CreateProductStatistics", ReplyAction="*")]
        WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse CreateProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/CreateProductStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse> CreateProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://ws.unit05.example2-data/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/UpdateProductStatistics", ReplyAction="*")]
        WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse UpdateProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit05.example2-data/UpdateProductStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse> UpdateProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatistics", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequestBody Body;
        
        public GetStatisticsRequest() {
        }
        
        public GetStatisticsRequest(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStatisticsRequestBody {
        
        public GetStatisticsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsResponse", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponseBody Body;
        
        public GetStatisticsResponse() {
        }
        
        public GetStatisticsResponse(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2-data/")]
    public partial class GetStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.Statistics[] GetStatisticsResult;
        
        public GetStatisticsResponseBody() {
        }
        
        public GetStatisticsResponseBody(WS.Unit05.Example2.Application.WSClient.DataWS.Statistics[] GetStatisticsResult) {
            this.GetStatisticsResult = GetStatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductStatistics", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequestBody Body;
        
        public GetProductStatisticsRequest() {
        }
        
        public GetProductStatisticsRequest(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2-data/")]
    public partial class GetProductStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetProductStatisticsRequestBody() {
        }
        
        public GetProductStatisticsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductStatisticsResponse", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponseBody Body;
        
        public GetProductStatisticsResponse() {
        }
        
        public GetProductStatisticsResponse(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2-data/")]
    public partial class GetProductStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long GetProductStatisticsResult;
        
        public GetProductStatisticsResponseBody() {
        }
        
        public GetProductStatisticsResponseBody(long GetProductStatisticsResult) {
            this.GetProductStatisticsResult = GetProductStatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProductStatistics", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequestBody Body;
        
        public CreateProductStatisticsRequest() {
        }
        
        public CreateProductStatisticsRequest(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2-data/")]
    public partial class CreateProductStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public CreateProductStatisticsRequestBody() {
        }
        
        public CreateProductStatisticsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProductStatisticsResponse", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponseBody Body;
        
        public CreateProductStatisticsResponse() {
        }
        
        public CreateProductStatisticsResponse(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateProductStatisticsResponseBody {
        
        public CreateProductStatisticsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductStatistics", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequestBody Body;
        
        public UpdateProductStatisticsRequest() {
        }
        
        public UpdateProductStatisticsRequest(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.unit05.example2-data/")]
    public partial class UpdateProductStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public UpdateProductStatisticsRequestBody() {
        }
        
        public UpdateProductStatisticsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductStatisticsResponse", Namespace="http://ws.unit05.example2-data/", Order=0)]
        public WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponseBody Body;
        
        public UpdateProductStatisticsResponse() {
        }
        
        public UpdateProductStatisticsResponse(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductStatisticsResponseBody {
        
        public UpdateProductStatisticsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap>, WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.GetStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest request) {
            return base.Channel.GetStatistics(request);
        }
        
        public WS.Unit05.Example2.Application.WSClient.DataWS.Statistics[] GetStatistics() {
            WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequestBody();
            WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse retVal = ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).GetStatistics(inValue);
            return retVal.Body.GetStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse> WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.GetStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest request) {
            return base.Channel.GetStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsResponse> GetStatisticsAsync() {
            WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.GetStatisticsRequestBody();
            return ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).GetStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.GetProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest request) {
            return base.Channel.GetProductStatistics(request);
        }
        
        public long GetProductStatistics(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequestBody();
            inValue.Body.name = name;
            WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse retVal = ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).GetProductStatistics(inValue);
            return retVal.Body.GetProductStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse> WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.GetProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest request) {
            return base.Channel.GetProductStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsResponse> GetProductStatisticsAsync(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.GetProductStatisticsRequestBody();
            inValue.Body.name = name;
            return ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).GetProductStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.CreateProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest request) {
            return base.Channel.CreateProductStatistics(request);
        }
        
        public void CreateProductStatistics(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequestBody();
            inValue.Body.name = name;
            WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse retVal = ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).CreateProductStatistics(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse> WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.CreateProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest request) {
            return base.Channel.CreateProductStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsResponse> CreateProductStatisticsAsync(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.CreateProductStatisticsRequestBody();
            inValue.Body.name = name;
            return ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).CreateProductStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.UpdateProductStatistics(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest request) {
            return base.Channel.UpdateProductStatistics(request);
        }
        
        public void UpdateProductStatistics(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequestBody();
            inValue.Body.name = name;
            WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse retVal = ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).UpdateProductStatistics(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse> WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap.UpdateProductStatisticsAsync(WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest request) {
            return base.Channel.UpdateProductStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsResponse> UpdateProductStatisticsAsync(string name) {
            WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest inValue = new WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequest();
            inValue.Body = new WS.Unit05.Example2.Application.WSClient.DataWS.UpdateProductStatisticsRequestBody();
            inValue.Body.name = name;
            return ((WS.Unit05.Example2.Application.WSClient.DataWS.DataServiceSoap)(this)).UpdateProductStatisticsAsync(inValue);
        }
    }
}
