//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Unit05.Example2.Application.WSClient.FedexWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.task1.unit03.ws/", ConfigurationName="WSClient.FedexWS.IFedexWS")]
    public interface IFedexWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.task1.unit03.ws/IFedexWS/shippingRequest", ReplyAction="http://webservices.task1.unit03.ws/IFedexWS/shippingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse shipping(WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.task1.unit03.ws/IFedexWS/shippingRequest", ReplyAction="http://webservices.task1.unit03.ws/IFedexWS/shippingResponse")]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse> shippingAsync(WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.task1.unit03.ws/")]
    public partial class shippingDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime deadLineField;
        
        private bool deadLineFieldSpecified;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime deadLine {
            get {
                return this.deadLineField;
            }
            set {
                this.deadLineField = value;
                this.RaisePropertyChanged("deadLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deadLineSpecified {
            get {
                return this.deadLineFieldSpecified;
            }
            set {
                this.deadLineFieldSpecified = value;
                this.RaisePropertyChanged("deadLineSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shipping", WrapperNamespace="http://webservices.task1.unit03.ws/", IsWrapped=true)]
    public partial class shippingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.task1.unit03.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.task1.unit03.ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.task1.unit03.ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg2;
        
        public shippingRequest() {
        }
        
        public shippingRequest(double arg0, double arg1, double arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shippingResponse", WrapperNamespace="http://webservices.task1.unit03.ws/", IsWrapped=true)]
    public partial class shippingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.task1.unit03.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WS.Unit05.Example2.Application.WSClient.FedexWS.shippingDetails @return;
        
        public shippingResponse() {
        }
        
        public shippingResponse(WS.Unit05.Example2.Application.WSClient.FedexWS.shippingDetails @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFedexWSChannel : WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FedexWSClient : System.ServiceModel.ClientBase<WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS>, WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS {
        
        public FedexWSClient() {
        }
        
        public FedexWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FedexWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FedexWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FedexWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS.shipping(WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest request) {
            return base.Channel.shipping(request);
        }
        
        public WS.Unit05.Example2.Application.WSClient.FedexWS.shippingDetails shipping(double arg0, double arg1, double arg2) {
            WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest inValue = new WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse retVal = ((WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS)(this)).shipping(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse> WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS.shippingAsync(WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest request) {
            return base.Channel.shippingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Unit05.Example2.Application.WSClient.FedexWS.shippingResponse> shippingAsync(double arg0, double arg1, double arg2) {
            WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest inValue = new WS.Unit05.Example2.Application.WSClient.FedexWS.shippingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WS.Unit05.Example2.Application.WSClient.FedexWS.IFedexWS)(this)).shippingAsync(inValue);
        }
    }
}
